version: "3.9"
services:
  mysql:
    image: mysql:8.0.26
    environment:
      - CLEARDB_DATABASE_URL=eu-cdbr-west-01.cleardb.com
    ports:
      - "3307:3307"
  payment-gw:
    image: payment-gw
    environment:
      - MYSQL_HOST=mysql
      - SPRING_RABBITMQ_HOST=rabbit
      - SPRING_RABBITMQ_PORT=5672
    ports:
      - "8080:8080"
    depends_on:
      - rabbit
  rabbit:
    image: rabbitmq:3-management
    environment:
      CLOUDAMQP_ONYX_URL: 'amqps://kikizolp:cTzep8HyiSbC6WB7aVJCsHZLheMKGyfG@bonobo.rmq.cloudamqp.com/kikizolp'
    ports:
      - "5672:5672"
      - "15672:15672"