version: "3.9"
services:
  mysql:
    image: mysql:8.0.26
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=payments
    ports:
      - "3306:3306"
  payment-gw:
    image: payment-gw
    environment:
      - MYSQL_HOST=mysql
      - SPRING_RABBITMQ_HOST=rabbit
      - SPRING_RABBITMQ_PORT=5672
    ports:
      - "8080:8080"
    depends_on:
      - rabbit
  rabbit:
    image: rabbitmq:3.9.5
    ports:
      - "5672:5672"
      - "15692:15692"
    environment:
      - AMQP_URL=amqps://kikizolp:cTzep8HyiSbC6WB7aVJCsHZLheMKGyfG@bonobo.rmq.cloudamqp.com/kikizolp
      - RABBITMQ_DEFAULT_USER=kikizolp
      - RABBITMQ_DEFAULT_PASS=cTzep8HyiSbC6WB7aVJCsHZLheMKGyfG